batch_size: 16000
half_res: True 
loadpath: ./models/Three_Images/1724048710.9041233.pth
datapath: ./data/nerf_synthetic/lego
savepath: ./results/lego
exp_name: mynerf_25_imgs
im_set: test 
im_idxs: [0,1,2,3,4,5,50,55,56,57,58,59] # renders rgb and depth for these indices from im_set
animation: True # if True, only renders video 
num_poses: 30
theta: 30